CREATE TABLE [dbo].[TBL_GRUPOS] (
    [ID]          INT            NOT NULL,
    [NOMBRE]      NVARCHAR (100) NOT NULL,
    [DESCRIPCION] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBL_GRUPOS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

