CREATE TABLE [dbo].[TBL_USUARIOS] (
    [ID]     INT            NOT NULL,
    [NOMBRE] NVARCHAR (100) NOT NULL,
    [EMAIL]  NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBL_USUARIOS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

