CREATE TABLE [dbo].[TBL_USUARIOS_GRUPOS] (
    [IDUSUARIO] INT NOT NULL,
    [IDGRUPO]   INT NOT NULL,
    CONSTRAINT [FK_TBL_USUARIOS_GRUPOS_TBL_GRUPOS] FOREIGN KEY ([IDGRUPO]) REFERENCES [dbo].[TBL_GRUPOS] ([ID]),
    CONSTRAINT [FK_TBL_USUARIOS_GRUPOS_TBL_USUARIOS] FOREIGN KEY ([IDUSUARIO]) REFERENCES [dbo].[TBL_USUARIOS] ([ID])
);

